/* eslint-disable no-use-before-define */
/* eslint-disable @typescript-eslint/no-empty-interface */
interface IBasicLayout {
	children: React.ReactNode;
}

interface IBanner {
	color?: string;
	bgColor?: string;
	title?: string;
	summary?: string;
	quote?: string;
}

interface IBannerLayout extends IBanner {
	children: React.ReactNode;
}

interface IProject {
	id: number;
	title: string;
	summary: string;
}

interface ITitledComponent {
	className?: string;
	title?: string;
}

interface ISocialIcon {
	brandName: string;
	brandUrl?: string;
}

interface IAddTitle {
	title?: string;
	children: React.ReactNode;
}

interface Post {
	id: number;
	title: string;
	summary: string;
	image: string;
}

interface Posts {
	posts: Post[];
}

// Generated by https://quicktype.io

interface SummaryProps {
	ID: string;
	Message: string;
	Global: Global;
	Countries: Country[];
	Date: string;
}

interface Country {
	ID: string;
	Country: string;
	CountryCode: string;
	Slug: string;
	NewConfirmed: number;
	TotalConfirmed: number;
	NewDeaths: number;
	TotalDeaths: number;
	NewRecovered: number;
	TotalRecovered: number;
	Date: string;
	Premium: Premium;
}

interface Premium {}

interface Global {
	NewConfirmed: number;
	TotalConfirmed: number;
	NewDeaths: number;
	TotalDeaths: number;
	NewRecovered: number;
	TotalRecovered: number;
	Date: string;
}
